[[headers]]
  for = "/music/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "audio/mpeg"
    Access-Control-Allow-Origin = "*"
    Accept-Ranges = "bytes"

[[headers]]
  for = "/*.mp3"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "audio/mpeg"
    Access-Control-Allow-Origin = "*"
    Accept-Ranges = "bytes"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Path = {exclude = ["/music/*", "/*.mp3"]}}
